CREATE TABLE "sessions" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "session_id" VARCHAR,
    "user_id" INT NOT NULL,
    "expires_at" TIMESTAMP NOT NULL,
     FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);